import React from "react";

const notes = [
  {
    symbol: "♪",
    left: "10%",
    top: "20%",
    size: "text-4xl",
    delay: "0s",
    color: "text-primary",
    opacity: "opacity-20",
    hover: "note-hover-0",
  },
  {
    symbol: "♫",
    left: "80%",
    top: "30%",
    size: "text-4xl",
    delay: "1s",
    color: "text-primary",
    opacity: "opacity-20",
    hover: "note-hover-1",
  },
  {
    symbol: "♪",
    left: "20%",
    top: "60%",
    size: "text-4xl",
    delay: "2s",
    color: "text-primary",
    opacity: "opacity-20",
    hover: "note-hover-2",
  },
  {
    symbol: "♫",
    left: "70%",
    top: "70%",
    size: "text-4xl",
    delay: "3s",
    color: "text-primary",
    opacity: "opacity-20",
    hover: "note-hover-3",
  },
  {
    symbol: "♪",
    left: "40%",
    top: "15%",
    size: "text-4xl",
    delay: "4s",
    color: "text-primary",
    opacity: "opacity-20",
    hover: "note-hover-4",
  },
  {
    symbol: "♫",
    left: "90%",
    top: "80%",
    size: "text-4xl",
    delay: "5s",
    color: "text-primary",
    opacity: "opacity-20",
    hover: "note-hover-5",
  },
  {
    symbol: "♬",
    left: "15%",
    top: "80%",
    size: "text-3xl",
    delay: "6s",
    color: "text-secondary",
    opacity: "opacity-15",
    hover: "note-hover-6",
  },
  {
    symbol: "♩",
    left: "60%",
    top: "10%",
    size: "text-3xl",
    delay: "7s",
    color: "text-secondary",
    opacity: "opacity-15",
    hover: "note-hover-7",
  },
  {
    symbol: "♬",
    left: "5%",
    top: "40%",
    size: "text-3xl",
    delay: "1.5s",
    color: "text-primary",
    opacity: "opacity-15",
    hover: "note-hover-0",
  },
  {
    symbol: "♪",
    left: "50%",
    top: "50%",
    size: "text-5xl",
    delay: "2.5s",
    color: "text-secondary",
    opacity: "opacity-[0.12]",
    hover: "note-hover-1",
  },
  {
    symbol: "♩",
    left: "85%",
    top: "15%",
    size: "text-3xl",
    delay: "3.5s",
    color: "text-primary",
    opacity: "opacity-[0.18]",
    hover: "note-hover-2",
  },
  {
    symbol: "♫",
    left: "30%",
    top: "85%",
    size: "text-4xl",
    delay: "4.5s",
    color: "text-secondary",
    opacity: "opacity-[0.16]",
    hover: "note-hover-3",
  },
  {
    symbol: "♪",
    left: "65%",
    top: "45%",
    size: "text-3xl",
    delay: "5.5s",
    color: "text-primary",
    opacity: "opacity-[0.14]",
    hover: "note-hover-4",
  },
  {
    symbol: "♬",
    left: "25%",
    top: "35%",
    size: "text-4xl",
    delay: "6.5s",
    color: "text-secondary",
    opacity: "opacity-[0.17]",
    hover: "note-hover-5",
  },
  {
    symbol: "♫",
    left: "95%",
    top: "55%",
    size: "text-3xl",
    delay: "7.5s",
    color: "text-primary",
    opacity: "opacity-[0.13]",
    hover: "note-hover-6",
  },
  {
    symbol: "♩",
    left: "45%",
    top: "75%",
    size: "text-5xl",
    delay: "0.5s",
    color: "text-secondary",
    opacity: "opacity-[0.11]",
    hover: "note-hover-7",
  },
  {
    symbol: "♪",
    left: "75%",
    top: "25%",
    size: "text-3xl",
    delay: "1.8s",
    color: "text-primary",
    opacity: "opacity-[0.19]",
    hover: "note-hover-0",
  },
  {
    symbol: "♬",
    left: "12%",
    top: "50%",
    size: "text-4xl",
    delay: "2.8s",
    color: "text-secondary",
    opacity: "opacity-[0.14]",
    hover: "note-hover-1",
  },
  {
    symbol: "♫",
    left: "55%",
    top: "90%",
    size: "text-3xl",
    delay: "3.8s",
    color: "text-primary",
    opacity: "opacity-[0.16]",
    hover: "note-hover-2",
  },
  {
    symbol: "♩",
    left: "88%",
    top: "65%",
    size: "text-4xl",
    delay: "4.8s",
    color: "text-secondary",
    opacity: "opacity-15",
    hover: "note-hover-3",
  },
];

const FloatingMusicNotes: React.FC = () => {
  return (
    <div className="fixed inset-0 overflow-hidden z-0 select-none">
      {notes.map((note, i) => (
        <span
          key={i}
          className={`absolute ${note.size} animate-float ${note.hover} pointer-events-auto transition-all duration-300 ${note.color} ${note.opacity}`}
          style={{
            left: note.left,
            top: note.top,
            animationDelay: note.delay,
            userSelect: "none",
          }}
        >
          {note.symbol}
        </span>
      ))}
    </div>
  );
};

export default FloatingMusicNotes;
